### PR TITLE
Towards crypto & method agility: API updates, new buffer, new credential struct

### PR DESCRIPTION
**Pull request by geonnave**
Still very early stage.

### CODE REVIEW

**Comment by geonnave** [comment]
So far this PR includes:
- updates in the API
  - support for setting different methods and crypto suites (even though only one is supported for now)
  - a separate function for setting identity (private key + credential)
- a new buffer struct that is parameterizeable via const generics
- a new credential struct that supports CCS's that hold asymmetric and symmetric keys
- improved handling of ID_CRED_x, including support for kids longer than 1 byte

Next steps are to update the examples and C/Python wrappers, then merge on main and continue the agility work on a new PR.

**Comment by geonnave** [comment]
@malishav just asked for a review, mostly interested in an ack about the changeset (in comment above).

One point I have is that the Symmetric key type would not need to live in `main`, but not keeping it in `main` means having to keep another version of the code just for that, which in my opinion is not worth it.

**Comment by geonnave** [comment]
Also, regarding actual crypto agility, I will leave for another PR since this one is already big enough...

**Review by malishav — APPROVED** [review]
I went briefly over the PR, it is massive, congrats on pulling this off! I am happy if you merge this!

**Pull request merged**
